### PR TITLE
handle no clipboard more gracefully, prints to stdout

### LINKED ISSUE #26: panics if clipboard copying is not available
this occurs in some setups when using SSH. Instead of panicking, it should still write the output to a file.

### PR DESCRIPTION
**Pull request by perstarkse**
Small change to handle no clipboard error without panicking, will print to sdtout if no clipboard. Will close #26 

Seems like some minor formatting changes got included as well due to auto-formatter, let me know if that's a issue.

### CODE REVIEW

**Comment by adc22** [comment]
This fixed the the clipboard panic error for me, but the exclude function isn't working as intended with globs, listing many filetypes

**Comment by perstarkse** [comment]
> This fixed the the clipboard panic error for me, but the exclude function isn't working as intended with globs, listing many filetypes

And the exclude function works as normal when not using this commit? I see there’s a reported issue about the exclude functionality.

**Comment by HmmIsThisThingOn** [comment]
The other commit didn't work for me, but yeah, probably not your issue :) Sorry, I'm by all measures unqualified to have a github account

**Comment by perstarkse** [comment]
> The other commit didn't work for me, but yeah, probably not your issue :) Sorry, I'm by all measures unqualified to have a github account

No worries at all, reporting bugs and testing are large parts to making open source software great! 
Looking at the code affected by this commit I suspect that the bug isn’t introduced here, but sometimes unexpected things happen :)

**Comment by mufeedvh** [comment]
Thank you so much @perstarkse for the PR! Merging now! ❤️ 🙌

**Pull request merged**
